### ISSUE TITLE
Error in 'demo.py'

### ISSUE THREAD

**Issue by Kundo2002** [isarandi/metrabs#53]
Hi, thank you for your great work. I wanted to try your demo, but it keeps giving my an error at model loading. following is the error message.

```
Traceback (most recent call last):
  File "/home/kundolee/PycharmProjects/Changup/metrabs-master/demo.py", line 95, in <module>
    main()
  File "/home/kundolee/PycharmProjects/Changup/metrabs-master/demo.py", line 9, in main
    model = tf.saved_model.load('/home/kundolee/.keras/models/metrabs_eff2l_y4')
  File "/home/kundolee/anaconda3/envs/spinningup/lib/python3.7/site-packages/tensorflow/python/saved_model/load.py", line 859, in load
    return load_internal(export_dir, tags, options)["root"]
  File "/home/kundolee/anaconda3/envs/spinningup/lib/python3.7/site-packages/tensorflow/python/saved_model/load.py", line 890, in load_internal
    ckpt_options, filters)
  File "/home/kundolee/anaconda3/envs/spinningup/lib/python3.7/site-packages/tensorflow/python/saved_model/load.py", line 160, in __init__
    self._load_all()
  File "/home/kundolee/anaconda3/envs/spinningup/lib/python3.7/site-packages/tensorflow/python/saved_model/load.py", line 256, in _load_all
    self._load_nodes()
  File "/home/kundolee/anaconda3/envs/spinningup/lib/python3.7/site-packages/tensorflow/python/saved_model/load.py", line 434, in _load_nodes
    node, setter = self._recreate(proto, node_id)
  File "/home/kundolee/anaconda3/envs/spinningup/lib/python3.7/site-packages/tensorflow/python/saved_model/load.py", line 551, in _recreate
    raise ValueError("Unknown SavedObject type: %r" % kind)
ValueError: Unknown SavedObject type: None
```

it says the type of 'kind' is None at 'node_id' 17258. Thank you.

I'm using
CUDA 11.0
cudnn 8.0.5
tensorflow 2.4.0

Also tried with
CUDA 11.2
cudnn 8.1.1
as #22 suggested

**Comment by EvanJamesMG** [comment]
same problem ,anyone sloved?

**Comment by isarandi** [comment]
I've pushed some major refactoring work, so this should be fixed already.
